export default {
  'user should be able to search for recipes': (browser) => {
    browser
      .url('http://localhost:8080')
      .waitForElementVisible('body', 2000)
      .pause(1000)
      .moveToElement('input#search-input', 20, 20)
      .pause(500)
      .setValue('input#search-input', 'rice')
      .moveToElement('a#search-button', 5, 5)
      .pause(500)
      .click('a#search-button')
      .pause(2000)
      .assert.urlEquals('http://localhost:8080/catalog?search=title&list=rice')
      .waitForElementVisible('body', 2000)
      .pause(2000)
      .moveToElement('input#search-input', 20, 20)
      .pause(500)
      .setValue('input#search-input', 'spaghetti')
      .moveToElement('a#search-button', 5, 5)
      .pause(500)
      .click('a#search-button')
      .pause(2000)
      .moveToElement('input#search-input', 20, 20)
      .pause(500)
      .clearValue('input#search-input')
      .pause(500)
      .setValue('input#search-input', 'corn flour')
      .moveToElement('a#search-button', 5, 5)
      .pause(500)
      .click('a#search-button')
      .pause(2000)
      .moveToElement('select#search-by', 20, 20)
      .pause(500)
      .moveToElement('option[value=ingredients]', 20, 20)
      .pause(500)
      .click('option[value=ingredients]')
      .moveToElement('a#search-button', 5, 5)
      .pause(500)
      .click('a#search-button')
      .pause(2000)
      .end();
  },
};
