export const validRecipeSeed = [{
  title: 'Beans',
  category: 'Dessert',
  description: 'Tasty beans',
  preparationTime: 65,
  ingredients: 'Beans, red oil, onion, salt, maggi, pepper',
  directions: 'Cook the beans and add the ingredients',
  recipeImage: 'Beans URL',
}, {
  title: 'Yam sauce',
  category: 'Lunch',
  description: 'Served white and colorful',
  preparationTime: 50,
  ingredients: 'Yam, tomatoes, egg, salt, maggi, pepper',
  directions: 'Slice the yam and prepare the sauce',
  recipeImage: 'Yam URL',
}, {
  title: 'Beans',
  category: 'Appetizer',
  description: 'Tasty and nutritious beans',
  preparationTime: 80,
  ingredients: 'Beans, red oil, onion, salt, maggi, pepper',
  directions: 'Cook the beans and add the ingredients',
  recipeImage: 'Beans URL',
}, {
  title: 'Egusi soup',
  category: 'Dinner',
  description: 'Tasty and nutritious soup',
  preparationTime: 65,
  ingredients: 'Egusi, stock fish, red oil, onion, salt, maggi, pepper',
  directions: 'Cook the egusi and add the ingredients',
  recipeImage: 'Egusi URL',
}, {
  title: 'Yam sauce',
  category: 'Lunch',
  description: 'Served white and colorful',
  preparationTime: 50,
  ingredients: 'Yam, tomatoes, vegetable oil, egg, salt, maggi, pepper',
  directions: 'Slice the yam and prepare the sauce',
  recipeImage: 'Url',
}, {
  title: 'Ogbono soup',
  category: 'Main',
  description: 'Tasty ogbono soup',
  preparationTime: 60,
  ingredients: 'Ogbono, palm oil, salt, stock fish',
  directions: 'Do this, do this. do that',
  recipeImage: 'Ogbono URL',
}];

export const invalidRecipeSeed = [{
  title: '   ',
  category: 'Lunch',
  description: 'Served white and colorful',
  preparationTime: 50,
  ingredients: 'Yam, tomatoes, egg, salt, maggi, pepper',
  directions: 'Slice the yam and prepare the sauce',
  recipeImage: 'Url',
}, {
  title: 'Yam sauce',
  category: 'Breakfast',
  description: '   ',
  preparationTime: 50,
  ingredients: 'Yam, tomatoes, egg, salt, maggi, pepper',
  directions: 'Slice the yam and prepare the sauce',
  recipeImage: 'Url',
}, {
  title: 'Yam sauce',
  category: 'Main',
  description: 'Served white and colorful',
  preparationTime: null,
  ingredients: 'Yam, tomatoes, egg, salt, maggi, pepper',
  directions: 'Slice the yam and prepare the sauce',
  recipeImage: 'Url',
}, {
  title: 'Yam sauce',
  category: 'Dinner',
  description: 'Served white and colorful',
  preparationTime: 50,
  ingredients: '   ',
  directions: 'Slice the yam and prepare the sauce',
  recipeImage: 'Url',
}, {
  title: 'Yam sauce',
  category: 'Breakfast',
  description: 'Served white and colorful',
  preparationTime: 50,
  ingredients: 'Yam, tomatoes, egg, salt, maggi, pepper',
  directions: '   ',
  recipeImage: 'Url',
}, {
  title: 'Spaghetti',
  category: '  ',
  description: 'Served white and colorful',
  preparationTime: 50,
  ingredients: 'Yam, tomatoes, egg, salt, maggi, pepper',
  directions: 'Slice the yam and prepare the sauce',
  recipeImage: 'Url',
}];

export const userFavoriteCategory = [{
  category: 'Lunch',
}];
